extends Node
enum Group { PLAYER, CAMERA, PROJECTILE, SPELLS }
enum DamageType { FORCE, ACID, FIRE, SLASHING, PIERCING, BLUDGEONING, COLD, LIGHTNING, THUNDER, POISON, RADIANT, NECROTIC }
enum StatusEffectType { STUN, SLOW, HASTE, BUFF, ENFEEBLE, BLINDED, FRIGHTENED, RESTRAINED, LETHARGY, VIGOR, NIMBLE, CUMBERSOME }
enum AiMode { STATIONARY, WANDER, PATROL, ENGAGED }
enum TwistType { DAMAGE, DAMAGE_OVER_TIME, STATUS_EFFECT }
enum Target { PLAYER, ENEMY, GROUND }
enum Facing { UP, DOWN, LEFT, RIGHT }
enum Direction { E, SE, S, SW, W, NW, N, NE }
enum MeleeMode { SWING, THRUST }
enum ParticleEffectType { NONE, FIRE, FROST }
